spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:kakeibo}
    username: ${POSTGRES_USER:kakeibo}
    password: ${POSTGRES_PASSWORD:kakeibo_local_dev}
  sql:
    init:
      mode: always